eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
#    enabled: false
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: guanfei
    url: jdbc:mysql:///cloud?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
env: dev
name: gf
1
