spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: guanfei
    url: jdbc:mysql:///cloud?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
